name: Coverage

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'


jobs:
  coverage:
    runs-on: ubuntu-latest  # Works on Windows/macOS too, adjust if needed
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Ensures Git history is available for Coveralls

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: llvm-tools-preview  # Needed for cargo-llvm-cov

      - name: Install cargo-llvm-cov
        uses: taiki-e/install-action@cargo-llvm-cov

      - name: Generate coverage data
        working-directory: winc-rs
        run: |
          cargo llvm-cov --lcov --output-path lcov.info

      - name: Coveralls GitHub Action
        uses: coverallsapp/github-action@v2.3.6
